# Generated by Django 3.1.3 on 2021-01-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210123_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='created_at',
        ),
    ]
